---
title: "Individual_Project_Pastor#2"
author: "Vincent Pastor"
date: "2022-12-11"
output: html_document
---


```{r, include = TRUE}
library(syuzhet)
library(plotly)
library(tidytext)
library(dplyr)
library(ggplot2)
library(twitteR)
```

```{r, include = TRUE}
# SETUP CREDENTIALS.
CONSUMER_KEY <- "AVkKX52SdvJHVkL8FKkiWx1Zl"
CONSUMER_SECRET <- "rX4kXD8LJbeNa8p19MCQvEIjhNXLa5gyBBeAhorC3C2dCpgh1Y"
ACCESS_TOKEN <-  "1595206858142121986-NZNHhytlvCoFo7eAFlNomofNthZLFk"
ACCESS_SECRET <-  "K7qSpHI15utrwDkoI3OwOHHg6IlwKT5RO0QQXwgvhcdIu"

setup_twitter_oauth(consumer_key = CONSUMER_KEY,
                    consumer_secret = CONSUMER_SECRET,
                    access_token = ACCESS_TOKEN,
                    access_secret = ACCESS_SECRET)
```

```{r, include = TRUE}
# EXTRACTING TWEETS.
trendTweets2 <- searchTwitter("#taylorswift", n=10000, lang="en", since="2022-12-01", until="2022-12-07", retryOnRateLimit = 120)
trendTweets2
```

```{r, include = TRUE}
# CONVERTING LIST DATA TO DATA FRAME.
trendTweetsDF2 <- twListToDF(trendTweets2)
class(trendTweetsDF2)
names(trendTweetsDF2)
View(trendTweetsDF2)
head(trendTweetsDF2)[1:5]
head(trendTweetsDF2$text)[1:5]
```

```{r, include = TRUE}
# SAVE DATA FRAME FILE.
save(trendTweetsDF2,file = "trendingTweetsDF1.Rdata")
```

```{r, include = TRUE}
# LOAD DATA FRAME FILE.
load(file = "trendingTweetsDF1.Rdata")
```

```{r, include = TRUE}
# SAVING FILE AS RDATA.
save(trendTweetsDF2, file = "tweetsDF2.Rdata")
```

```{r, include = TRUE}
# CHECKING FOR MISSING VALUES IN A DATA FRAME.
sap2 <- sapply(trendTweetsDF2, function(x) sum(is.na(x)))
sap2
```

```{r, include = TRUE}
# SUBSETTING TWEETS.
sub <- trendTweetsDF2 %>%
  select(screenName,text,created, isRetweet) %>% filter(isRetweet == FALSE)
sub
```

```{r, include = TRUE}
# GROUPING THE DATA CREATED. 
sub %>%  
  group_by(1) %>%  
  summarise(max = max(created), min = min(created))

grp <- sub %>%  mutate(Created_At_Round = created %>% round(units = 'hours') %>% as.POSIXct())
grp

sub %>% pull(created) %>% min() 
sub %>% pull(created) %>% max()
```

```{r, include = TRUE}
# Plot on tweets by time using the library(plotly) and ggplot().
plt2 <- ggplot(grp, aes(x = Created_At_Round)) +
  geom_histogram(aes(fill = ..count..)) +
  theme(legend.position = "right") +
  xlab("Time") + ylab("Number of tweets") + 
  scale_fill_gradient(low = "midnightblue", high = "aquamarine4")


plt2 %>% ggplotly()
```
# ==============================================

```{r, include = TRUE}
# SUBSETTING RETWEETS.
sub2 <- trendTweetsDF2 %>%
  select(screenName,text,created, isRetweet) %>% filter(isRetweet == TRUE)
sub2

sub2 %>%  
  group_by(1) %>%  
  summarise(max = max(created), min = min(created))

grp2 <- sub2 %>%  mutate(Created_At_Round = created %>% round(units = 'hours') %>% as.POSIXct())
grp2

sub2 %>% pull(created) %>% min() 
sub2 %>% pull(created) %>% max()
```

```{r, include = TRUE}
# Plot on tweets by time using the library(plotly) and ggplot().
plt3 <- ggplot(grp2, aes(x = Created_At_Round)) +
  geom_histogram(aes(fill = ..count..)) +
  theme(legend.position = "right") +
  xlab("Time") + ylab("Number of tweets") + 
  scale_fill_gradient(low = "midnightblue", high = "aquamarine4")


plt3 %>% ggplotly()
```
